### ISSUE TITLE
Double-checking: 403 Error?

### ISSUE THREAD

**Issue by SeanKilleen** [estruyf/github-visitors-badge#3]
Hey! Thanks for all the work you do around the profile visitor badges etc. -- very cool stuff.

I'm not sure how I originally found it, but I've been using the following in my GitHub Profile: `
![Visitors since 11 Nov 2020](http://estruyf-github.azurewebsites.net/api/VisitorHit?user=SeanKilleen&repo=SeanKilleen&countColor=%237B1E7A)`

As of today (possibly earlier), `http://estruyf-github.azurewebsites.net/` is returning a 403 for everything, causing the image to break.

I totally don't expect you to host this for free, even if it is an Azure Function. Just looking for clarity. Is this host going away? Should I have migrated somewhere else? Should I ideally be self-hosting this? 

Thanks in advance for your thoughts!

**Comment by estruyf** [comment]
I am closing the issue as it is long overdue on my end. This had to do with a change in the API that had to be made because some person was DDOS-ing the service.

> More info: https://www.eliostruyf.com/ddos-azure-functions-front-door/
